# MORE SECURE OPTION IS TO STORE PASSWORD IN ENVIRONMENT VARS
mail:
  mail_server: smtp.gmail.com
  mail_username: fitness_management
  # password = admin1
  mail_password: gAAAAABiAPdTi0xFO3VqRUB1jtkMuv1we4_rOwJ1y4AAjNq2bOqVDooJ04cZ1r013r-Iol-Iuskrwl3_PqfUbDy-ptCh8oHCbQ==
  mail_port: 587
  mail_use_ssl: False
  mail_use_tls: True
